src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MessagesRepository;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'messages')]
    private $author;

    #[ORM\Column(type: 'string', length: 100)]
    private $Subject;

    #[ORM\Column(type: 'text')]
    private $Message;

    #[ORM\ManyToOne(targetEntity: Contact::class, inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private $contact;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->Subject;
    }

    public function setSubject(string $Subject): self
    {
        $this->Subject = $Subject;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    public function setContact(?Contact $contact): self
    {
        $this->contact = $contact;

        return $this;
    }
}

templates/styleguide/components/15-molecules/messages-received/messages-received.html.twig
{% set componentClass = 'm-messagesReceived' %}
{% set attributeList = attributeList is defined ? attributeList : {} %}
{% set attributeList = attributeList|merge({'class': (attributeList.class is defined ? componentClass ~' ' ~ attributeList.class : componentClass)}) %}

<div {% for attribute, value in attributeList %} {{ attribute }}="{{ value }}"{% endfor %}>
    {% if contacts %}
      {% for contact in contacts %}
      <div class="m-messagesReceived__wrapper">
        <div class="m-messagesReceived__head js-messages-display">
          <div class="m-messagesReceived__title">
            {# to cut the name after 25 characters #}
            <p class="a-p -primary">{{ contact.fullName|length > 25 ? contact.fullName|slice(0, 25) ~ '...' : contact.fullName }}</p>
            <img src="/icons/open.svg" alt="open" >
          </div>
          <p class="a-textDetails">{{ contact.createdAt|date('d/m/Y H:i') }}</p>
        </div>
        <div class="m-messagesReceived__content">
          <p>{{ contact.subject }}</p>
          <p>{{ contact.message }}</p>
          <div class="m-messagesReceived__buttons">
            {% include '@atom/button/button.html.twig' with {
              text: "Supprimer",
              attributeList: {
                  class: '-alertGhost',
                  href: path('delete_contactMessage-admin', {id : contact.id}),
                  onclick:"confirm('Voulez vous vraiment supprimer ce message?') || event.preventDefault()",
                  title:"Supprimer le message",
              }
            } only %}
            {% include '@atom/button/button.html.twig' with {
                text: "Répondre",
                attributeList: {
                    class: '-primaryGhost',
                    href: path('app_dashboardMessage-admin', {id : contact.id}),
                    title: "Répondre",
                }
            } only %}
          </div>
        </div> 

      </div>

      {% endfor %}
    {% else %}
    <p> Vous n'avez aucun message </p>
    {% endif %}
  </div>